name: Pull Request Build

on:
  pull_request:
    types: [opened, synchronize]
    # paths:
    #   - '**.kicad_sch'
    #   - '**.kicad_pcb'
    #   - '**.kicad_pro'

jobs:
  expose-pr-number:
    name: Expose PR Number
    runs-on: ubuntu-latest
    steps:
      - name: Expose PR ID
        run: echo "${{ github.event.number }}" > pr-number.txt

      - name: Upload PR ID
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr-number.txt